stages:
  - build
  - deploy

variables:
  BUCKET_NAME: 360v2.mycw.in #put your main bucket here

build:
  stage: build
  image: node:12.19.1   #node:10.15.3

  cache:

    paths:
      - node_modules/
  script:
    #- set NODE_OPTIONS=--max_old_space_size=4096
    - npm install --progress=false
    - BUCKET_NAME=$BUCKET_NAME CI=false npm run build #put your build script here
  artifacts:
    expire_in: 1 hour
    paths:
      - build/ ##this is the directory your site builds into
  only:
    - master

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync ./build s3://$BUCKET_NAME --delete #your build directory#

    # Invalidate the cloudfront cache to make the changes live
    - aws cloudfront create-invalidation --distribution-id E3S3EEE26CFKEW --paths "/*"


  only:
    - master


